### PR TITLE
Update gem fog json to 1.1

### PR DESCRIPTION
**Pull request by AlexLamande**

### CODE REVIEW

**Comment by AlexLamande** [comment]
oops need to update fog-core

**Comment by AlexLamande** [comment]
@KevinLoiseau @ybart updated gems and launched `rake test`, it passed, are we ok?

**Comment by AlexLamande** [comment]
@KevinLoiseau we're not using fog's gem so why opening a PR on their side?

**Comment by KevinLoiseau** [comment]
@AlexLamande because we want to use it, they are just really slow for take opensource contribution but we have to move this problematic off as soon as possible.

**Pull request merged**
